import {Renderer} from './renderer.js';
const $=id=>document.getElementById(id),esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=new URLSearchParams(location.search).get('token');let state,renderer,busy=false,piece=null,bufferData=null,chips=Array(35).fill(0),renderGeneration=0;
const defaults={'KeyN':'suggest','Enter':'commit','Escape':'cancel','Control+KeyZ':'undo','Control+Shift+KeyZ':'redo','F9':'checkpoint','Control+KeyF':'filter','Control+KeyG':'focus','KeyB':'buffers','Tab':'nextPiece','Shift+Tab':'previousPiece','KeyH':'halfTurn','KeyT':'thirdTurn','Shift+KeyT':'inverseThirdTurn','BracketLeft':'previousPreset','BracketRight':'nextPreset','Control+KeyH':'toggleReference'};
let keybinds={...defaults};
const builtins={'Active orbit':[{expr:'active',style:'solid'}],'Unsolved orbit':[{expr:'active & unsolved',style:'solid'}],'Orientation only':[{expr:'active & orientation_wrong',style:'highlight'}],'Work cell':[{expr:'current(C000)',style:'solid'}],'All pieces':[{expr:'everything',style:'solid'}]};
function message(t,error=false){$('message').textContent=t;$('message').style.color=error?'#ff9d8e':'#a6bbd0';}
async function api(path,data){
 const opt={headers:{'X-C600-Token':token}};if(data!==undefined){opt.method='POST';opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(data);}
 const res=await fetch('/api/'+path,opt);const j=await res.json();if(!res.ok||j.error)throw Error(j.error||res.statusText);
 if(j.job){
  window.c600.currentJob=j.job;
  message('Computing the full operation. Camera controls remain available.');
  while(true){await new Promise(r=>setTimeout(r,80));const x=await api('job/'+j.job);if(x.done){window.c600.currentJob=null;if(x.error)throw Error(x.error);return x.result;}}
 }
 return j;
}
async function binary(path){const r=await fetch(path,{headers:{'X-C600-Token':token}});if(!r.ok)throw Error(await r.text());return r.arrayBuffer();}
async function run(fn){if(busy)return;busy=true;window.dispatchEvent(new CustomEvent('c600:busy',{detail:true}));try{await fn();}catch(e){console.error(e);message(e.message,true);}finally{busy=false;window.dispatchEvent(new CustomEvent('c600:busy',{detail:false}));}}
function active(){return Number($('orbit').value);}
function target(){const s=$('destination').value;return s===''?null:Number(s);}
function drawRules(rules){$('rules').innerHTML='';for(const r of rules){const div=document.createElement('div');div.className='rule';div.innerHTML=`<div class="row"><select class="ruleStyle">${['solid','ghost','highlight','hide'].map(x=>`<option ${x===r.style?'selected':''}>${x}</option>`).join('')}</select><button class="removeRule">Remove</button></div><input class="ruleExpr" value="${esc(r.expr)}" aria-label="Filter expression">`;div.querySelector('button').onclick=()=>div.remove();div.querySelector('input').addEventListener('keydown',e=>{if(e.key==='Enter'){e.stopPropagation();run(applyFilter);}});$('rules').append(div);}}
function readRules(){
 let r=[...$('rules').children].map(n=>({expr:n.querySelector('input').value,style:n.querySelector('select').value}));let inc=chips.flatMap((x,i)=>x===1?['O'+String(i).padStart(2,'0')]:[]),exc=chips.flatMap((x,i)=>x===-1?['O'+String(i).padStart(2,'0')]:[]);let c=[];if(inc.length)c.push('('+inc.join(' | ')+')');if(exc.length)c.push('!('+exc.join(' | ')+')');if(c.length)r=r.map(x=>({...x,expr:'('+x.expr+') & '+c.join(' & ')}));return r;
}
async function applyFilter(){await api('prefs',{rules:readRules(),pin_safety:$('pin').checked});chips.fill(0);updateChips();await refresh();drawRules(state.prefs.rules);message('Filters applied before draw-list construction. All hidden pieces remain active in mechanics.');}
function updateChips(){[...$('orbitChips').children].forEach((b,i)=>{b.className=chips[i]===1?'include':chips[i]===-1?'exclude':'';b.textContent=(chips[i]===1?'+':chips[i]===-1?'−':'')+'O'+String(i).padStart(2,'0');});}
function allPresets(){return {...builtins,...(state?.prefs.presets||{})};}
function updatePresetOptions(){const old=$('preset').value;$('preset').innerHTML=Object.keys(allPresets()).map(x=>`<option>${esc(x)}</option>`).join('');if(allPresets()[old])$('preset').value=old;}
async function usePreset(name){let r=allPresets()[name];if(name==='Work cell')r=[{expr:`current(C${String(Number($('focus').value)).padStart(3,'0')})`,style:'solid'}];if(!r)return;drawRules(r);chips.fill(0);updateChips();await api('prefs',{rules:r});await refresh();$('preset').value=name;}
async function cyclePreset(dir){const listed=state.prefs.filter_sequence;const names=Array.isArray(listed)&&listed.length?listed.filter(x=>allPresets()[x]):Object.keys(allPresets());if(!names.length)return;const i=names.indexOf($('preset').value);await usePreset(names[(i+dir+names.length)%names.length]);}
function updateCertificate(){
 const c=state.pending;$('commit').disabled=!c;$('certExport').disabled=!c;
 if(!c){$('certificate').innerHTML='<span class="muted">Preview a legal operation to inspect its complete support and certificate.</span>';return;}
 const conflicts=c.support.filter(r=>state.prefs.protected.includes(r.orbit));$('commit').disabled=conflicts.length>0;
 $('certificate').innerHTML=`<span class="badge">RETAINED MODEL · WITNESSED OPERATION</span><div>${esc(c.note)}</div><p><span class="metric">${c.star_count.toLocaleString()}<small> stars</small></span><span class="metric">${Number(c.primitive_count).toLocaleString()}<small> turns</small></span></p><div>${c.net_moved_pieces.toLocaleString()} pieces · ${c.net_moved_stickers.toLocaleString()} stickers affected</div><div class="mono">${esc(c.certificate_id.slice(0,26))}…</div>${conflicts.length?'<p class="bad">Blocked: protected '+conflicts.map(r=>'O'+String(r.orbit).padStart(2,'0')).join(', ')+'</p>':'<p class="good">No protected-orbit intersection.</p>'}<details><summary>All target and collateral support</summary><table><thead><tr><th>Orbit</th><th>Pieces</th><th>Stickers</th></tr></thead><tbody>${c.support.map(r=>`<tr><td>O${String(r.orbit).padStart(2,'0')}</td><td>${r.pieces}</td><td>${r.stickers}</td></tr>`).join('')}</tbody></table><div class="mono">Pre ${esc(c.pre_state)}<br>Post ${esc(c.post_state)}</div></details><div class="hint">${esc(c.assistance)}. Full-puzzle collateral executes atomically. Native Windows equivalence is not certified.</div>`;
}
async function refresh(){
 const gen=++renderGeneration;state=await api('status');$('orbit').value=state.prefs.orbit;$('pin').checked=state.prefs.pin_safety;
 $('headline').textContent=`${state.moving_solved.toLocaleString()} / ${state.moving_total.toLocaleString()} moving pieces solved · ${state.stars.toLocaleString()} stars · ${Number(state.primitives).toLocaleString()} primitives`;
 $('solvedTotal').textContent=(100*state.moving_solved/state.moving_total).toFixed(2)+'%';$('stageCount').textContent=state.progress.filter(x=>x.solved===x.pieces).length+' / 35';
 $('undo').disabled=!state.can_undo;$('redo').disabled=!state.can_redo;$('protect').textContent=state.prefs.protected.includes(active())?'Unprotect orbit':'Protect orbit';
 $('progress').querySelector('tbody').innerHTML=state.progress.map(r=>`<tr data-orbit="${r.orbit}" class="${r.orbit===active()?'active':''}"><td>${state.prefs.protected.includes(r.orbit)?'◆ ':''}O${String(r.orbit).padStart(2,'0')}</td><td class="${r.solved===r.pieces?'ok':''}">${r.solved}/${r.pieces}</td><td>${r.position_wrong}</td><td>${r.orientation_wrong}</td></tr>`).join('');
 $('progress').querySelectorAll('tbody tr').forEach(tr=>tr.onclick=()=>run(()=>setOrbit(Number(tr.dataset.orbit))));
 const old=$('checkpoints').value;$('checkpoints').innerHTML=state.checkpoints.map(c=>`<option value="${esc(c.name)}">${esc(c.name)} · #${c.head}</option>`).join('');if(state.checkpoints.some(c=>c.name===old))$('checkpoints').value=old;
 updateCertificate();if(renderer){const [lb,sb]=await Promise.all([binary('/api/labels'),binary('/api/styles')]);if(gen===renderGeneration){const labels=new Uint32Array(lb);renderer.setState(labels,new Uint8Array(sb));for(let c=0;c<600;c++){let n=0;for(let j=c*433;j<(c+1)*433;j++)if(labels[j]===j)n++;const b=$('cellAtlas').children[c];if(b){b.style.background=`hsl(165 28% ${12+20*n/433}%)`;b.title=`C${c}: ${n}/433 exact stickers`;}}}}
 if(state.prefs.selected!==null){const tracked=await api('track-piece',{piece:state.prefs.selected});showPiece(tracked);}
 window.c600.state=state;window.dispatchEvent(new CustomEvent('c600:state',{detail:state}));
}
async function setOrbit(o){$('destination').value='';await api('prefs',{orbit:o});await refresh();bufferData=null;$('bufferInfo').textContent='Analyze this orbit’s buffers and the destination to inspect available frames.';message('Active orbit O'+String(o).padStart(2,'0'));}
function showPiece(p){piece=p;$('piecePos').value=p.position;$('pieceInfo').innerHTML=`<b>P${p.piece}</b> at position <b>P${p.position}</b> · O${String(p.orbit).padStart(2,'0')}<br>Home colors: ${p.home_cells.map(x=>'C'+x).join(' ')}<br>Current cells: ${p.current_cells.map(x=>'C'+x).join(' ')}<br><span class="${p.solved?'good':''}">${p.solved?'Exactly solved':p.orientation_wrong?'Correct position; orientation incorrect':'Position incorrect'}</span><details><summary>Sticker identities and cap membership</summary><div class="mono">Slots ${p.slots.join(', ')}<br>Labels ${p.labels.join(', ')}<br>Caps ${p.cap_cells.join(', ')}</div></details>`;}
async function selectPosition(p){const info=await api('select',{position:p});showPiece(info);await refresh();}
async function analyzeBuffers(){const o=active();bufferData=await api('buffers',{orbit:o,target:target()??($('piecePos').value===''?null:Number($('piecePos').value))});const b=bufferData;
 $('bufferInfo').innerHTML=`<b>Buffer A: P${b.A.position}</b> contains P${b.A.piece}<br><b>Buffer B: P${b.B.position}</b> contains P${b.B.piece}<br>Reference C: P${b.third}<br><span class="good">${b.reachable.toLocaleString()} / ${b.expected.toLocaleString()} oriented setup states</span><br>Setup depth: mean ${b.mean_depth.toFixed(2)}, maximum ${b.max_depth}<details><summary>Guarded cells</summary><div class="mono">${b.guard_cells.map(x=>'C'+x).join(' ')}</div></details><div class="hint">The buffers are fixed positions during setup. Their occupants move when the star executes.</div>`;
 $('frames').innerHTML=b.candidates.map(r=>`<div class="frameRow" data-node="${r.node}">Node <b>${r.node}</b> · ${r.length.toLocaleString()} primitives · setup ${r.depth}<br><span class="mono">${r.slots.join(', ')}</span></div>`).join('')||'<div class="hint">Select a nonbuffer position in this orbit for its 1–60 frame options.</div>';
 $('frames').querySelectorAll('[data-node]').forEach(n=>n.onclick=()=>{$('node').value=n.dataset.node;message('Frame node selected. Use Preview star to inspect all collateral.');});}
async function download(path,name){const r=await fetch('/api/'+path,{headers:{'X-C600-Token':token}});if(!r.ok){const e=await r.json();throw Error(e.error);}const blob=await r.blob();const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function parseWord(text){return text.trim().split(/[\s,]+/).filter(Boolean).map(t=>{if(/^-?\d+$/.test(t))return Number(t);const r=/^([HT])(\d+)(')?$/i.exec(t);if(!r||Number(r[2])>=600)throw Error('Use H0, T0, T0\' or signed integer IDs.');const m=2*Number(r[2])+(r[1].toUpperCase()==='H'?1:2);return r[3]?-m:m;});}
async function previewRecipe(recipe,note=''){await api('preview',{recipe,note});await refresh();message('Preview ready. Review support and confirm with Enter.');}
async function suggest(){const r=await api('suggest',{orbit:active(),batch:Number($('batch').value),target:target()});await refresh();message(r.complete?r.note:'Assisted insertion preview ready. No move has been applied.');}
async function commit(){if(!state.pending)throw Error('No preview');const c=state.pending;await api('commit',{token:c.token});const animation=window.c600.pendingAnimation;window.c600.pendingAnimation=null;if(animation&&animation.certificate===c.certificate_id&&document.getElementById('turnAnimation').checked)await renderer.animateTurn(animation.info,animation.mask);await refresh();message('Committed '+Number(c.primitive_count).toLocaleString()+' witnessed primitives as one transaction.');}
async function checkpoint(){await api('prefs',{view:renderer.view()});const c=await api('checkpoint',{});await refresh();message('Saved '+c.name+' at head #'+c.head);}
async function nextPiece(dir){
 const o=active(),s=state.prefs.selected,pos=Number($('piecePos').value||0);let from=pos;
 // Read exact labels once; search physical slots without rendering/picking hidden geometry.

 // Active-orbit candidates are obtained from the precomputed setup tree via the analyzer only when selected.
 const r=await api('next-piece',{orbit:o,position:from,direction:dir});await selectPosition(r.position);$('focus').value=r.current_cells[0];renderer.focus(r.current_cells[0]);
}
const actions={suggest,commit,cancel:async()=>{await api('cancel',{});await refresh();},undo:async()=>{await api('undo',{});await refresh();message('Undo restored the exact previous state.');},redo:async()=>{await api('redo',{});await refresh();},checkpoint,filter:()=>{$('rules').querySelector('input')?.focus();},focus:()=>{$('focus').focus();$('focus').select();},buffers:analyzeBuffers,nextPiece:()=>nextPiece(1),previousPiece:()=>nextPiece(-1),halfTurn:()=>previewRecipe([{kind:'word',moves:[2*Number($('focus').value)+1]}],'Focus-cell H turn'),thirdTurn:()=>previewRecipe([{kind:'word',moves:[2*Number($('focus').value)+2]}],'Focus-cell T turn'),inverseThirdTurn:()=>previewRecipe([{kind:'word',moves:[-(2*Number($('focus').value)+2)]}],'Inverse focus-cell T turn'),previousPreset:()=>cyclePreset(-1),nextPreset:()=>cyclePreset(1),toggleReference:()=>{renderer.reference=!renderer.reference;renderer.dirty=true;$('referenceFlag').hidden=!renderer.reference;}};
window.addEventListener('keydown',e=>{
 if(document.querySelector('dialog[open]'))return;if(e.code==='Escape'&&window.c600.currentJob){e.preventDefault();api('stop-job',{}).catch(err=>message(err.message,true));return;}const typing=['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.target.isContentEditable;if(typing)return;
 const code=[e.ctrlKey?'Control':'',e.altKey?'Alt':'',e.shiftKey?'Shift':'',e.metaKey?'Meta':'',e.code].filter(Boolean).join('+'),a=keybinds[code];if(!a)return;
 if((a==='nextPiece'||a==='previousPiece') && e.target.tagName!=='CANVAS' && e.target!==document.body)return;
 e.preventDefault();if(e.repeat)return;run(()=>actions[a]());
});
function bind(id,fn){$(id).addEventListener('click',()=>run(fn));}
bind('undo',actions.undo);bind('redo',actions.redo);bind('save',checkpoint);bind('suggest',suggest);bind('commit',commit);bind('cancel',actions.cancel);bind('buffers',analyzeBuffers);
bind('applyFilter',applyFilter);bind('addRule',()=>drawRules([...readRules(),{expr:'nothing',style:'solid'}]));bind('clearChips',()=>{chips.fill(0);updateChips();});$('pin').onchange=()=>run(applyFilter);
$('orbit').onchange=()=>run(()=>setOrbit(active()));bind('protect',async()=>{let p=[...state.prefs.protected],o=active();p=p.includes(o)?p.filter(x=>x!==o):[...p,o];await api('prefs',{protected:p});await refresh();});
bind('nextStage',async()=>{const o=state.order.find(o=>state.progress[o].solved<state.progress[o].pieces);if(o===undefined)return message('Every moving orbit is solved.');await setOrbit(o);});
$('preset').onchange=()=>run(()=>usePreset($('preset').value));bind('savePreset',async()=>{const n=prompt('Preset name');if(!n)return;await api('prefs',{presets:{...(state.prefs.presets||{}),[n.slice(0,60)]:readRules()}});await refresh();updatePresetOptions();$('preset').value=n;});bind('prevPreset',()=>cyclePreset(-1));bind('nextPreset',()=>cyclePreset(1));
bind('focusGo',()=>{renderer.focus(Number($('focus').value));$('scene').focus();});$('focus').addEventListener('keydown',e=>{if(e.key==='Enter'){e.stopPropagation();renderer.focus(Number($('focus').value));$('scene').focus();}});bind('local',()=>usePreset('Work cell'));$('detail').onchange=()=>{renderer.mode=$('detail').value;renderer.rebuild();};bind('reference',actions.toggleReference);
$('cellScale').oninput=()=>{renderer.cellScale=Number($('cellScale').value);renderer.dirty=true;};$('stickerScale').oninput=()=>{renderer.stickerScale=Number($('stickerScale').value);renderer.dirty=true;};$('d4').oninput=()=>{renderer.distance4=Number($('d4').value);renderer.dirty=true;};
bind('inspect',()=>selectPosition(Number($('piecePos').value)));bind('findHome',()=>{if(!piece)return;const c=piece.home_cells[0];$('focus').value=c;renderer.focus(c);});bind('useDest',()=>{if(!piece)return;$('destination').value=piece.position;message('Fixed destination P'+piece.position+' selected. Clear its field for automatic target choice.');});bind('findResident',async()=>{if(!piece)return;const destination=piece.position;$('destination').value=destination;const r=await api('find-required',{position:destination});await selectPosition(r.position);$('focus').value=r.current_cells[0];renderer.focus(r.current_cells[0]);});
bind('star',()=>previewRecipe([{kind:'star',orbit:active(),node:Number($('node').value),sign:Number($('sign').value)}],'Manually selected star'));bind('wordPreview',()=>previewRecipe([{kind:'word',moves:parseWord($('word').value)}],'Manually entered word'));bind('demo',async()=>{await api('demo',{});await refresh();message('Demo scramble preview ready. Enter applies it.');});bind('certExport',()=>download('certificate','macro_certificate.c600.json'));
bind('restore',async()=>{if(!confirm('Restore this checkpoint on its original branch? Other branches remain in the journal.'))return;await api('restore',{name:$('checkpoints').value});await refresh();drawRules(state.prefs.rules);renderer.restore(state.prefs.view);message('Checkpoint restored. Previous branch preserved.');});bind('backup',async()=>{const r=await api('backup',{});message('Consistent SQLite backup saved: '+r.path);});bind('export',()=>download('export','session.c600.json.gz'));bind('import',()=>$('importFile').click());
$('importFile').onchange=()=>run(async()=>{const f=$('importFile').files[0];if(!f)return;if(f.size>20*1024*1024)throw Error('Interactive import maximum is 20 MB.');let stream=f.stream();if(f.name.endsWith('.gz'))stream=stream.pipeThrough(new DecompressionStream('gzip'));const reader=stream.getReader(),chunks=[];let total=0;while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>20*1024*1024){reader.cancel();throw Error('Decompressed interactive record exceeds 20 MB.');}chunks.push(value);}const text=await new Blob(chunks).text();await api('import',{record:JSON.parse(text)});await refresh();message('Imported proof history replayed and verified before activation.');});
bind('keys',()=>{$('keyJson').value=JSON.stringify(keybinds,null,2);$('keyDialog').showModal();});bind('closeKeys',()=>$('keyDialog').close());bind('resetKeys',()=>{$('keyJson').value=JSON.stringify(defaults,null,2);});bind('saveKeys',async()=>{const b=JSON.parse($('keyJson').value);if(!b||Array.isArray(b)||typeof b!=='object'||Object.keys(b).length>100)throw Error('Expected up to 100 key/action entries.');for(const [k,v] of Object.entries(b)){if(!actions[v])throw Error('Unknown action: '+v);if(!/^(?:(?:Control|Alt|Shift|Meta)\+)*(?:Key[A-Z]|Digit[0-9]|F[1-9][0-9]?|Enter|Escape|Tab|Space|BracketLeft|BracketRight)$/.test(k))throw Error('Unsupported physical key code: '+k);}keybinds=b;await api('prefs',{keybinds:b});await refresh();$('keyDialog').close();message('Keybindings saved.');});
bind('benchmark',async()=>{message('Measuring synchronous draw time on this browser and GPU.');const r=await renderer.benchmark(90);window.c600.lastBenchmark=r;const u=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='c600_browser_benchmark.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);message(`Measured frame interval p50 ${r.raf_interval_p50_ms.toFixed(1)} ms; p95 ${r.raf_interval_p95_ms.toFixed(1)} ms (${r.mode}).`);});
window.c600={api,refresh,actions,selectPosition,analyzeBuffers,parseWord,run,previewRecipe,drawRules,usePreset,setOrbit,download,message,getState:()=>state};
async function start(){
 const meta=await (await fetch('/assets/mesh.json')).json();const [v,l,c,f,sp,n]=await Promise.all(['mesh_vertices.f32','mesh_sticker.u32','mesh_centers.f32','cell_frames.f32','slot_piece.u32','cell_normals.f32'].map(x=>binary('/assets/'+x)));window.c600.slotPiece=new Uint32Array(sp);
 for(let o=0;o<35;o++){const op=document.createElement('option');op.value=o;op.textContent='O'+String(o).padStart(2,'0');$('orbit').append(op);const b=document.createElement('button');b.onclick=()=>{chips[o]=chips[o]===0?1:chips[o]===1?-1:0;updateChips();};$('orbitChips').append(b);}updateChips();
 for(let c=0;c<600;c++){const b=document.createElement('button');b.textContent=String(c).padStart(3,'0');b.onclick=()=>{$('focus').value=c;renderer.focus(c);};$('cellAtlas').append(b);}
 renderer=new Renderer($('scene'),meta,{vertices:new Float32Array(v),local:new Uint32Array(l),centers:new Float32Array(c),frames:new Float32Array(f),normals:new Float32Array(n)},(slot,event)=>run(()=>{if(event?.ctrlKey){const cell=Math.floor(slot/433);$('focus').value=cell;renderer.focus(cell);window.dispatchEvent(new Event('c600:focus'));return;}return selectPosition(window.c600.slotPiece[slot]);}),r=>{if(r.error)return message(r.error,true);$('performance').textContent=`${r.visible.toLocaleString()} stickers · ${r.mode==='mesh'?'cut solids':'overview glyphs'} · draw-list ${r.build_ms.toFixed(1)} ms`;});window.c600.renderer=renderer;
 await refresh();drawRules(state.prefs.rules);keybinds=state.prefs.keybinds||defaults;updatePresetOptions();renderer.restore(state.prefs.view);$('detail').value=renderer.mode;$('focus').value=renderer.focusCell;
 message(/SwiftShader|llvmpipe|software/i.test(renderer.gpu)?'Software graphics renderer detected. Full state is ready, but camera performance may be limited.':'Full state ready. Preview a turn, star or assisted insertion. Checkpoints and proof history are local.');$('performance').title=renderer.gpu;window.c600.ready=true;window.dispatchEvent(new Event('c600:ready'));
}
start().catch(e=>{console.error(e);message(e.message,true);window.c600.error=e.message;});
