/* Compact puzzle-first shell. Original mechanics API is retained. */
const $=id=>document.getElementById(id),escapeText=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let app,catalog=[],currentPanel='filters',lastFocus=-1,currentGrips=[],historyBefore=null,clock={seconds:0,running:false},clockAt=performance.now(),saveHandle=null;
const on=(id,fn)=>$(id)?.addEventListener('click',()=>app.run(fn));
function panel(name){currentPanel=name;document.body.classList.remove('hideDock');document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('selected',x.dataset.name===name));document.querySelectorAll('#dockTabs button').forEach(x=>x.classList.toggle('selected',x.dataset.panel===name));if(name==='history')loadHistory();if(name==='progress')loadStats();saveLayout();}
function saveLayout(){clearTimeout(saveHandle);saveHandle=setTimeout(()=>{if(!app)return;app.api('prefs',{layout:{panel:currentPanel,theme:document.body.dataset.theme,side:document.body.classList.contains('dockLeft')?'left':'right',width:parseInt(getComputedStyle(document.documentElement).getPropertyValue('--dock')),hidden:document.body.classList.contains('hideDock')},view:app.renderer.view()}).catch(e=>app.message(e.message,true));},400);}
function theme(name){document.body.dataset.theme=name==='dark'?'dark':'classic';if(app?.renderer){app.renderer.background=name==='dark'?[.085,.09,.10]:[.13,.145,.16];app.renderer.dirty=true;}saveLayout();}
function toggleDock(){document.body.classList.toggle('hideDock');saveLayout();}
async function loadStats(){const x=await app.api('stats');clock=x.timer;clockAt=performance.now();$('statsDetails').innerHTML=`<div class="help">Scramble: ${BigInt(x.scramble_primitives).toLocaleString()} turns<br>Solution: ${BigInt(x.solution_primitives).toLocaleString()} turns<br>${x.assisted_transactions.toLocaleString()} assisted transactions</div>`;}
async function loadHistory(more=false){const r=await app.api('history'+(more&&historyBefore!==null?'?before='+historyBefore:''));historyBefore=r.next_before;if(!more)$('historyList').innerHTML='';for(const x of r.rows){const node=document.createElement('div');node.className=x.id===r.head?'current':'';node.innerHTML=`<div class="entryTop"><b>#${x.id} ← ${x.parent??'root'}</b><button>Checkout</button></div><div>${escapeText(x.note)}</div><small>${BigInt(x.primitive_count).toLocaleString()} turns · ${escapeText(x.assistance)}</small>`;node.querySelector('button').onclick=()=>app.run(async()=>{if(!confirm('Checkout event #'+x.id+'? Current and other branches will be retained.'))return;await app.api('checkout',{head:x.id});await app.refresh();await loadHistory();});$('historyList').append(node);}$('historyMore').disabled=historyBefore===null;}
function typeTree(){if(!catalog.length)return;const key=$('typeGrouping').value,groups=new Map();for(const r of catalog){const k=r[key];if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);}const root=$('typeTree');root.innerHTML='';for(const [k,rows] of [...groups].sort((a,b)=>a[0]-b[0])){const d=document.createElement('details');d.open=true;d.className='typeGroup';d.innerHTML=`<summary>${key==='rank'?'Rank':'Stickers'} ${k} <span class="help">(${rows.length})</span></summary><div class="typeRows"></div>`;for(const row of rows){const b=document.createElement('button'),o=row.orbit;b.innerHTML=`<span>O${String(o).padStart(2,'0')}</span><small>${row.pieces.toLocaleString()}</small>`;b.title=`${row.stickers} sticker(s); ${row.orientation}. Click includes, then excludes, then clears.`;b.onclick=()=>{const original=$('orbitChips').children[o];original.click();b.className=original.className;};d.lastChild.append(b);}root.append(d);}}
async function refreshGrips(){if(!app?.ready&&!app?.renderer)return;const c=app.renderer.focusCell;if(c===lastFocus)return;lastFocus=c;const r=await app.api('grips?cell='+c);currentGrips=r.axes;const div=$('gripButtons');div.innerHTML='';for(let i=0;i<r.axes.length;i++){const a=r.axes[i],b=document.createElement('button');b.textContent=a.label;b.title=`${i+1}: ${a.order===2?'180°':'120°'} cap rotation; right-click for inverse`;b.onclick=()=>app.run(()=>previewGrip(i,false));b.oncontextmenu=e=>{e.preventDefault();app.run(()=>previewGrip(i,true));};div.append(b);}$('viewLabel').textContent=`Full 600-cell · C${String(c).padStart(3,'0')}`;}
async function previewGrip(i,inverse=false){await refreshGrips();const forward=currentGrips[i];if(!forward)throw Error('Grip unavailable');const info=inverse?{...forward.inverse,cell:forward.cell}:forward;await app.previewRecipe([{kind:'word',moves:info.word}],`C${info.cell} ${forward.label}${inverse?' inverse':''}`);const res=await fetch('/api/cap?cell='+info.cell,{headers:{'X-C600-Token':new URLSearchParams(location.search).get('token')}});if(!res.ok)throw Error('Cap mask request failed');app.pendingAnimation={info,certificate:app.state.pending?.certificate_id,mask:new Uint8Array(await res.arrayBuffer())};}
function updateLists(state){const p=state.prefs;$('macroLibrary').innerHTML='';for(const [name,item] of Object.entries(p.macro_library||{})){const d=document.createElement('div'),b=document.createElement('button');b.textContent=name;b.title=BigInt(item.primitive_count).toLocaleString()+' witnessed turns';b.onclick=()=>app.run(()=>app.previewRecipe(item.recipe,name));const inv=document.createElement('button');inv.textContent='Inverse';inv.onclick=()=>app.run(()=>app.api('compose',{a:item.recipe,operation:'inverse'}).then(()=>app.refresh()));d.append(b,inv);$('macroLibrary').append(d);}
 $('bookmarks').innerHTML='';for(const [name,view] of Object.entries(p.bookmarks||{})){const d=document.createElement('div'),b=document.createElement('button');b.textContent=name;b.onclick=()=>{app.renderer.restore(view);$('focus').value=app.renderer.focusCell;lastFocus=-1;refreshGrips();saveLayout();};d.append(b);$('bookmarks').append(d);}
 $('savedSets').textContent=Object.entries(p.named_sets||{}).map(([k,x])=>`${k}: ${x.ids.length} ${x.kind==='identity'?'identities':'positions'}`).join(' · ');
 const c=state.pending;$('previewToast').hidden=!c;if(c){const blocked=c.support.some(r=>p.protected.includes(r.orbit));$('previewSummary').textContent=`${blocked?'Protected conflict · ':''}${c.star_count} stars · ${BigInt(c.primitive_count).toLocaleString()} turns`;$('quickCommit').disabled=blocked;}
 const o=catalog[p.orbit];if(o)$('seedCard').innerHTML=`<b>O${String(o.orbit).padStart(2,'0')} target seed</b><br>${o.length.toLocaleString()} primitive turns<br><code>${escapeText(o.formula)}</code><br>Collateral: ${o.collateral.map(x=>'O'+String(x).padStart(2,'0')).join(', ')||'none'}`;
}
function readMacro(id){const el=$(id);if(el._recipe&&el.value===el._caption)return el._recipe;return [{kind:'word',moves:app.parseWord(el.value)}];}
async function setup(){app=window.c600;
 for(const el of document.querySelectorAll('[data-click]'))el.onclick=()=>$(el.dataset.click).click();
 for(const el of document.querySelectorAll('[data-panel]'))el.onclick=()=>panel(el.dataset.panel);
 for(const el of document.querySelectorAll('[data-theme-choice]'))el.onclick=()=>theme(el.dataset.themeChoice);
 document.querySelectorAll('.menu button').forEach(b=>b.addEventListener('click',()=>document.querySelectorAll('.menu').forEach(d=>d.open=false)));
 document.addEventListener('pointerdown',e=>{if(!e.target.closest('.menu'))document.querySelectorAll('.menu').forEach(d=>d.open=false);});
 $('toggleDock').onclick=$('toolToggle').onclick=$('closeDock').onclick=toggleDock;
 $('moveDock').onclick=()=>{document.body.classList.toggle('dockLeft');saveLayout();};
 $('fullScreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});};
 $('helpMenu').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();
 on('fit',()=>{app.renderer.fit();saveLayout();});$('cellOnly').onchange=()=>{app.renderer.setCellView($('cellOnly').checked);$('viewScope').textContent=$('cellOnly').checked?'Cell-only display; full mechanics retained':'All hosting cells displayed';saveLayout();};
 on('showAll',async()=>{app.renderer.setCellView(false);$('cellOnly').checked=false;$('viewScope').textContent='All hosting cells displayed';await app.usePreset('All pieces');app.renderer.zoom=1.1;app.renderer.dirty=true;});
 on('scrambleMenu',async()=>{const n=prompt('Number of legal random turns (1–10,000):','1000');if(n===null)return;await app.api('scramble',{count:Number(n)});await app.refresh();panel('solve');});
 on('quickCommit',()=>app.actions.commit());on('quickCancel',()=>app.actions.cancel());
 $('cancel').addEventListener('click',e=>{if(app.currentJob){e.stopImmediatePropagation();app.api('stop-job',{});}},true);
 on('saveSequence',async()=>{const names=$('presetSequence').value.split('\n').map(x=>x.trim()).filter(Boolean);const valid=[...$('preset').options].map(o=>o.value);if(names.some(n=>!valid.includes(n)))throw Error('Every entry must be an existing preset name');await app.api('prefs',{filter_sequence:names});await app.refresh();app.message('Preset sequence saved.');});
 on('saveSet',async()=>{const r=await app.api('save-set',{name:$('setName').value,expression:$('setExpr').value||'selected',kind:$('setKind').value});await app.refresh();app.message(`Saved ${r.members} ${r.kind} members as ${r.name}.`);});
 on('saveBookmark',async()=>{const n=$('bookmarkName').value.trim();if(!n)return;await app.api('prefs',{bookmarks:{...(app.state.prefs.bookmarks||{}),[n.slice(0,60)]:app.renderer.view()}});await app.refresh();});
 $('typeGrouping').onchange=typeTree;$('clearChips').addEventListener('click',()=>setTimeout(typeTree));$('applyFilter').addEventListener('click',()=>setTimeout(typeTree,100));
 on('historyRefresh',()=>loadHistory());on('historyMore',()=>loadHistory(true));
 on('namedCheckpoint',async()=>{const name=prompt('Checkpoint name');if(!name)return;await app.api('prefs',{view:app.renderer.view()});await app.api('checkpoint',{name});await app.refresh();});
 on('saveMacro',async()=>{await app.api('save-macro',{name:$('macroName').value});await app.refresh();});
 for(const [id,operation] of [['commutator','commutator'],['conjugate','conjugate'],['inverseA','inverse']])on(id,async()=>{await app.api('compose',{a:readMacro('macroA'),b:operation==='inverse'?[]:readMacro('macroB'),operation});await app.refresh();panel('solve');});
 on('useLastA',()=>{if(!app.state.pending)throw Error('Preview an operation first');const el=$('macroA');el._recipe=app.state.pending.recipe;el._caption=`Captured recipe: ${app.state.pending.star_count} stars, ${app.state.pending.primitive_count} primitives`;el.value=el._caption;});
 $('wireframe').onchange=()=>{app.renderer.wireframe=$('wireframe').checked;app.renderer.dirty=true;saveLayout();};$('pixelScale').onchange=()=>{app.renderer.pixelScale=Number($('pixelScale').value);app.renderer.dirty=true;saveLayout();};
 for(const id of ['cellScale','stickerScale','d4','detail'])$(id).addEventListener('change',saveLayout);
 for(let i=0;i<7;i++){app.actions['grip'+(i+1)]=()=>previewGrip(i,false);app.actions['inverseGrip'+(i+1)]=()=>previewGrip(i,true);}
 app.actions.toggleDock=toggleDock;app.actions.fit=()=>app.renderer.fit();
 const base={'KeyN':'suggest','Enter':'commit','Escape':'cancel','Control+KeyZ':'undo','Control+Shift+KeyZ':'redo','F9':'checkpoint','Control+KeyF':'filter','Control+KeyG':'focus','KeyB':'buffers','Tab':'nextPiece','Shift+Tab':'previousPiece','KeyH':'halfTurn','KeyT':'thirdTurn','Shift+KeyT':'inverseThirdTurn','BracketLeft':'previousPreset','BracketRight':'nextPreset','Control+KeyH':'toggleReference','F8':'toggleDock','KeyF':'fit'};
 $('keyClassic').onclick=()=>$('keyJson').value=JSON.stringify(base,null,2);
 $('keyGrip').onclick=()=>{const k={...base};for(let i=1;i<=7;i++){k['Digit'+i]='grip'+i;k['Shift+Digit'+i]='inverseGrip'+i;}$('keyJson').value=JSON.stringify(k,null,2);};
 window.addEventListener('keydown',e=>{if(e.code==='F8'&&!document.querySelector('dialog[open]')&&!app.state?.prefs.keybinds?.F8){e.preventDefault();if(!e.repeat)toggleDock();}});
 const splitter=$('dockSplitter');splitter.onpointerdown=e=>{splitter.setPointerCapture(e.pointerId);document.body.classList.add('dragging');};splitter.onpointermove=e=>{if(!document.body.classList.contains('dragging'))return;const left=document.body.classList.contains('dockLeft');let w=left?e.clientX:window.innerWidth-e.clientX;document.documentElement.style.setProperty('--dock',Math.max(240,Math.min(520,w))+'px');};splitter.onpointerup=()=>{document.body.classList.remove('dragging');saveLayout();};splitter.onpointercancel=()=>document.body.classList.remove('dragging');splitter.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const w=parseInt(getComputedStyle(document.documentElement).getPropertyValue('--dock'));document.documentElement.style.setProperty('--dock',Math.max(240,Math.min(520,w+(e.key==='ArrowLeft'?10:-10)))+'px');saveLayout();}};
 $('timerToggle').onclick=()=>app.run(async()=>{clock=await app.api('timer',{action:clock.running?'pause':'start'});clockAt=performance.now();});
 catalog=await app.api('catalog');typeTree();
 const l=app.state.prefs.layout;if(l){theme(l.theme);document.body.classList.toggle('dockLeft',l.side==='left');document.documentElement.style.setProperty('--dock',Math.max(240,Math.min(520,l.width||310))+'px');panel(l.panel||'filters');document.body.classList.toggle('hideDock',!!l.hidden);}else{await app.usePreset('Work cell');app.renderer.setCellView(true);theme('classic');}
 $('cellOnly').checked=app.renderer.displayHost!==null;$('viewScope').textContent=$('cellOnly').checked?'Cell-only display; full mechanics retained':'All hosting cells displayed';$('presetSequence').value=(app.state.prefs.filter_sequence||[]).join('\n');$('pixelScale').value=app.renderer.pixelScale;$('wireframe').checked=app.renderer.wireframe;
 updateLists(app.state);await refreshGrips();await loadStats();
 setInterval(()=>{refreshGrips().catch(()=>{});const seconds=clock.seconds+(clock.running?(performance.now()-clockAt)/1000:0);$('timerValue').textContent=[Math.floor(seconds/3600),Math.floor(seconds/60)%60,Math.floor(seconds)%60].map(x=>String(x).padStart(2,'0')).join(':');$('timerToggle').textContent=clock.running?'Pause':'Start timer';},500);
 setInterval(()=>{if(clock.running)app.api('timer',{action:'heartbeat'}).then(x=>{clock=x;clockAt=performance.now();}).catch(()=>{});},5000);
 app.shellReady=true;
}
window.addEventListener('c600:state',e=>{if(app)updateLists(e.detail);});
window.addEventListener('c600:busy',e=>{document.body.classList.toggle('analyzing',e.detail);});
window.addEventListener('c600:ready',()=>setup().catch(e=>window.c600.message(e.message,true)),{once:true});
